#ifndef GUARD_CONSTANTS_BXPY_H
#define GUARD_CONSTANTS_BXPY_H

enum BXPYBattleTypes
{
    BXPY_BATTLE_SINGLE,
    BXPY_BATTLE_DOUBLE,
    BXPY_BATTLE_MULTI_2v2,
    BXPY_BATTLE_MULTI_1v2,
    BXPY_BATTLE_MULTI_2v1,
};

enum BXPYErrorCodes
{
    BXPY_ERROR_BRING_SIZE_TOO_LARGE,
    BXPY_ERROR_BRING_SIZE_NOT_ENOUGH,
    BXPY_ERROR_CLAUSE_SPECIES,
    BXPY_ERROR_CLAUSE_ITEM,
    BXPY_ERROR_CLAUSE_SPECIAL_POKEMON,
};

enum BXPYHealModes
{
    BXPY_HEAL_NEVER,
    BXPY_HEAL_BEFORE_BATTLE,
    BXPY_HEAL_AFTER_BATTLE,
    BXPY_HEAL_ALWAYS,
    BXPY_HEAL_COUNT,
};

enum BXPYTeamPreviewItemModes
{
    BXPY_ITEM_NO_VISIBILITY,
    BXPY_ITEM_SHOW_POSSESSION,
    BXPY_ITEM_SHOW_ITEM,
};

enum BXPYTeamPreviewSpeciesModes
{
    BXPY_SPECIES_HIDE,
    BXPY_SPECIES_SHOW_BASE,
    BXPY_SPECIES_SHOW_TRUE,
};

#define VAR_BXPY_PICK_SIZE                       VAR_0x8008
#define VAR_BXPY_BRING_SIZE                      VAR_0x800B
#define VAR_BXPY_PARTNER                         VAR_0x800A

#define SUMMARY_SCREEN_SPRITE_ID_TYPE_1          SPRITE_ARR_ID_TYPE
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_2          SPRITE_ARR_ID_TYPE + 1
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_TERA       SPRITE_ARR_ID_TYPE + 2
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_1     SPRITE_ARR_ID_TYPE
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_2     SPRITE_ARR_ID_TYPE + 1
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_3     SPRITE_ARR_ID_TYPE + 2
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_4     SPRITE_ARR_ID_TYPE + 3

#endif //GUARD_CONSTANTS_BXPY_H
