#ifndef GUARD_CONSTANTS_BXPY_H
#define GUARD_CONSTANTS_BXPY_H

enum BXPYBattleTypes
{
    BXPY_BATTLE_SINGLE,
    BXPY_BATTLE_DOUBLE,
    BXPY_BATTLE_MULTI_2v2,
    BXPY_BATTLE_MULTI_1v2,
    BXPY_BATTLE_MULTI_2v1,
};

enum BXPYErrorCodes
{
    BXPY_ERROR_BRING_SIZE_TOO_LARGE,
    BXPY_ERROR_BRING_SIZE_NOT_ENOUGH,
    BXPY_ERROR_CLAUSE_SPECIES,
    BXPY_ERROR_CLAUSE_ITEM,
    BXPY_ERROR_CLAUSE_SPECIAL_POKEMON,
};

enum BXPYHealModes
{
    BXPY_HEAL_NEVER,
    BXPY_HEAL_BEFORE_BATTLE,
    BXPY_HEAL_AFTER_BATTLE,
    BXPY_HEAL_ALWAYS,
    BXPY_HEAL_COUNT,
};

#define VAR_BXPY_PICK_SIZE VAR_0x8008
#define VAR_BXPY_BRING_SIZE VAR_0x800B
#define VAR_BXPY_PARTNER VAR_0x800A

#endif //GUARD_CONSTANTS_BXPY_H
